import { useMemo } from 'react';
import type { FlowEditorChromeProps } from './FlowEditorChrome';
import type {
  BuildTopNavParams,
  BuildToolbarParams,
  BuildPlaybackParams,
  BuildEmptyStateParams,
  UseFlowEditorChromePropsParams,
} from './chromePropTypes';

export function buildFlowEditorTopNavProps({
  handleSwitchPage,
  handleAddPage,
  handleClosePage,
  handleRenamePage,
  handleExport,
  handleCopyImage,
  handleSvgExport,
  handleCopySvg,
  handlePdfExport,
  handleCinematicExport,
  handleExportJSON,
  handleCopyJSON,
  handleExportMermaid,
  handleDownloadMermaid,
  handleExportPlantUML,
  handleDownloadPlantUML,
  handleExportOpenFlowDSL,
  handleDownloadOpenFlowDSL,
  handleExportFigma,
  handleDownloadFigma,
  handleShare,
  handleImportJSON,
  openHistory,
  onGoHome,
  startPlayback,
  collaborationTopNavState,
}: BuildTopNavParams): FlowEditorChromeProps['topNav'] {
  return {
    onSwitchPage: handleSwitchPage,
    onAddPage: handleAddPage,
    onClosePage: handleClosePage,
    onRenamePage: handleRenamePage,
    onExportPNG: handleExport,
    onCopyImage: handleCopyImage,
    onExportSVG: handleSvgExport,
    onCopySVG: handleCopySvg,
    onExportPDF: handlePdfExport,
    onExportCinematic: handleCinematicExport,
    onExportJSON: handleExportJSON,
    onCopyJSON: handleCopyJSON,
    onExportMermaid: handleExportMermaid,
    onDownloadMermaid: handleDownloadMermaid,
    onExportPlantUML: handleExportPlantUML,
    onDownloadPlantUML: handleDownloadPlantUML,
    onExportOpenFlowDSL: handleExportOpenFlowDSL,
    onDownloadOpenFlowDSL: handleDownloadOpenFlowDSL,
    onExportFigma: handleExportFigma,
    onDownloadFigma: handleDownloadFigma,
    onShare: handleShare,
    onImportJSON: handleImportJSON,
    onHistory: openHistory,
    onGoHome,
    onPlay: startPlayback,
    collaboration: collaborationTopNavState,
  };
}

export function buildFlowEditorToolbarProps({
  currentStepIndex,
  openCommandBar,
  toggleStudioPanel,
  editorMode,
  handleAddShape,
  handleAddAnnotation,
  handleAddSection,
  handleAddTextNode,
  handleAddClassNode,
  handleAddEntityNode,
  handleAddMindmapNode,
  handleAddJourneyNode,
  handleAddArchitectureNode,
  handleAddSequenceParticipant,
  handleAddWireframe,
  undo,
  redo,
  handleLayoutWithContext,
  canUndo,
  canRedo,
  isSelectMode,
  enableSelectMode,
  isCommandBarOpen,
  enablePanMode,
  getCenter,
}: BuildToolbarParams): FlowEditorChromeProps['toolbar'] {
  return {
    isVisible: currentStepIndex === -1,
    onCommandBar: () => openCommandBar('root'),
    onToggleStudio: toggleStudioPanel,
    isStudioOpen: editorMode === 'studio',
    onOpenAssets: () => openCommandBar('assets'),
    onAddShape: handleAddShape,
    onAddAnnotation: handleAddAnnotation,
    onAddSection: handleAddSection,
    onAddTextNode: handleAddTextNode,
    onAddClassNode: handleAddClassNode,
    onAddEntityNode: handleAddEntityNode,
    onAddMindmapNode: handleAddMindmapNode,
    onAddJourneyNode: handleAddJourneyNode,
    onAddArchitectureNode: handleAddArchitectureNode,
    onAddSequenceParticipant: handleAddSequenceParticipant,
    onAddWireframe: handleAddWireframe,
    onUndo: undo,
    onRedo: redo,
    onLayout: handleLayoutWithContext,
    canUndo,
    canRedo,
    isSelectMode,
    onToggleSelectMode: enableSelectMode,
    isCommandBarOpen,
    onTogglePanMode: enablePanMode,
    getCenter,
  };
}

export function buildFlowEditorPlaybackProps({
  currentStepIndex,
  totalSteps,
  isPlaying,
  togglePlay,
  nextStep,
  prevStep,
  stopPlayback,
}: BuildPlaybackParams): FlowEditorChromeProps['playback'] {
  return {
    currentStepIndex,
    totalSteps,
    isPlaying,
    onPlayPause: togglePlay,
    onNext: nextStep,
    onPrev: prevStep,
    onStop: stopPlayback,
  };
}

export function buildFlowEditorEmptyStateProps({
  nodes,
  t,
  openStudioPanel,
  openCommandBar,
  handleAddNode,
  setPendingAIPrompt,
}: BuildEmptyStateParams): FlowEditorChromeProps['emptyState'] | undefined {
  if (nodes.length > 0) {
    return undefined;
  }

  return {
    title: t('flowEditor.emptyState.title', { defaultValue: 'Start your diagram' }),
    description: t('flowEditor.emptyState.description', {
      defaultValue:
        'Choose the fastest way to get a first draft on the canvas, then refine it with layout, properties, and Studio tools.',
    }),
    generateLabel: t('flowEditor.emptyState.generateWithFlowpilot', {
      defaultValue: 'Generate with Flowpilot',
    }),
    templatesLabel: t('flowEditor.emptyState.browseTemplates', {
      defaultValue: 'Browse templates',
    }),
    addNodeLabel: t('flowEditor.emptyState.addBlankNode', {
      defaultValue: 'Start from a blank node',
    }),
    onGenerate: () => openStudioPanel('ai'),
    onTemplates: () => openCommandBar('templates'),
    onAddNode: () => handleAddNode(),
    onSuggestionClick: (prompt) => {
      setPendingAIPrompt(prompt);
      openStudioPanel('ai');
    },
  };
}

export function useFlowEditorChromeProps(
  params: UseFlowEditorChromePropsParams
): Pick<FlowEditorChromeProps, 'topNav' | 'toolbar' | 'playback' | 'emptyState'> {
  const {
    handleSwitchPage,
    handleAddPage,
    handleClosePage,
    handleRenamePage,
    handleExport,
    handleCopyImage,
    handleSvgExport,
    handleCopySvg,
    handlePdfExport,
    handleCinematicExport,
    handleExportJSON,
    handleCopyJSON,
    handleExportMermaid,
    handleDownloadMermaid,
    handleExportPlantUML,
    handleDownloadPlantUML,
    handleExportOpenFlowDSL,
    handleDownloadOpenFlowDSL,
    handleExportFigma,
    handleDownloadFigma,
    handleShare,
    handleImportJSON,
    openHistory,
    onGoHome,
    startPlayback,
    collaborationTopNavState,
    currentStepIndex,
    toggleStudioPanel,
    editorMode,
    handleAddShape,
    handleAddAnnotation,
    handleAddSection,
    handleAddTextNode,
    handleAddClassNode,
    handleAddEntityNode,
    handleAddMindmapNode,
    handleAddJourneyNode,
    handleAddArchitectureNode,
    handleAddSequenceParticipant,
    handleAddWireframe,
    undo,
    redo,
    handleLayoutWithContext,
    canUndo,
    canRedo,
    isSelectMode,
    enableSelectMode,
    isCommandBarOpen,
    enablePanMode,
    getCenter,
    totalSteps,
    isPlaying,
    togglePlay,
    nextStep,
    prevStep,
    stopPlayback,
    nodes,
    t,
    openStudioPanel,
    openCommandBar,
    handleAddNode,
    setPendingAIPrompt,
  } = params;

  const topNav = useMemo(
    () =>
      buildFlowEditorTopNavProps({
        handleSwitchPage,
        handleAddPage,
        handleClosePage,
        handleRenamePage,
        handleExport,
        handleCopyImage,
        handleSvgExport,
        handleCopySvg,
        handlePdfExport,
        handleCinematicExport,
        handleExportJSON,
        handleCopyJSON,
        handleExportMermaid,
        handleDownloadMermaid,
        handleExportPlantUML,
        handleDownloadPlantUML,
        handleExportOpenFlowDSL,
        handleDownloadOpenFlowDSL,
        handleExportFigma,
        handleDownloadFigma,
        handleShare,
        handleImportJSON,
        openHistory,
        onGoHome,
        startPlayback,
        collaborationTopNavState,
      }),
    [
      handleSwitchPage,
      handleAddPage,
      handleClosePage,
      handleRenamePage,
      handleExport,
      handleCopyImage,
      handleSvgExport,
      handleCopySvg,
      handlePdfExport,
      handleCinematicExport,
      handleExportJSON,
      handleCopyJSON,
      handleExportMermaid,
      handleDownloadMermaid,
      handleExportPlantUML,
      handleDownloadPlantUML,
      handleExportOpenFlowDSL,
      handleDownloadOpenFlowDSL,
      handleExportFigma,
      handleDownloadFigma,
      handleShare,
      handleImportJSON,
      openHistory,
      onGoHome,
      startPlayback,
      collaborationTopNavState,
    ]
  );
  const toolbar = useMemo(
    () =>
      buildFlowEditorToolbarProps({
        currentStepIndex,
        openCommandBar,
        toggleStudioPanel,
        editorMode,
        handleAddShape,
        handleAddAnnotation,
        handleAddSection,
        handleAddTextNode,
        handleAddClassNode,
        handleAddEntityNode,
        handleAddMindmapNode,
        handleAddJourneyNode,
        handleAddArchitectureNode,
        handleAddSequenceParticipant,
        handleAddWireframe,
        undo,
        redo,
        handleLayoutWithContext,
        canUndo,
        canRedo,
        isSelectMode,
        enableSelectMode,
        isCommandBarOpen,
        enablePanMode,
        getCenter,
      }),
    [
      currentStepIndex,
      openCommandBar,
      toggleStudioPanel,
      editorMode,
      handleAddShape,
      handleAddAnnotation,
      handleAddSection,
      handleAddTextNode,
      handleAddClassNode,
      handleAddEntityNode,
      handleAddMindmapNode,
      handleAddJourneyNode,
      handleAddArchitectureNode,
      handleAddSequenceParticipant,
      handleAddWireframe,
      undo,
      redo,
      handleLayoutWithContext,
      canUndo,
      canRedo,
      isSelectMode,
      enableSelectMode,
      isCommandBarOpen,
      enablePanMode,
      getCenter,
    ]
  );
  const playback = useMemo(
    () =>
      buildFlowEditorPlaybackProps({
        currentStepIndex,
        totalSteps,
        isPlaying,
        togglePlay,
        nextStep,
        prevStep,
        stopPlayback,
      }),
    [currentStepIndex, totalSteps, isPlaying, togglePlay, nextStep, prevStep, stopPlayback]
  );
  const emptyState = useMemo(
    () =>
      buildFlowEditorEmptyStateProps({
        nodes,
        t,
        openStudioPanel,
        openCommandBar,
        handleAddNode,
        setPendingAIPrompt,
      }),
    [nodes, t, openStudioPanel, openCommandBar, handleAddNode, setPendingAIPrompt]
  );

  return {
    topNav,
    toolbar,
    playback,
    emptyState,
  };
}
